### ISSUE TITLE
Create "info" command 

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/mergin-cpp-client#5]
that will output at least `namespace/project` of the project as JSON on the stdout

```
cd projectfolder
mergin info 
> 
{
  namespace: "lutra"
  project: "myproject1"
  server: "public.mergincloud.com"
}
```

the `.mergin` subfolder contains information in file `mergin.json` so maybe just reusing that?

**Comment by wonder-sk** [comment]
- "status" instead of "stats" ?
- it would be nice if the default output was human-friendly for reading, and have JSON output optionally as a flag
